runtime: nodejs12

instance_class: F1

automatic_scaling:
  max_instances: 3
  max_concurrent_requests: 80
  target_throughput_utilization: 0.95
  target_cpu_utilization: 0.95
  max_pending_latency: 500ms
  min_pending_latency: 400ms

handlers:
- url: /$
  static_files: frontend/static/index.html
  upload: frontend/static/index.html

- url: /(.*\.html)$
  static_files: frontend/static/\1
  upload: frontend/static/.*\.html$

- url: /favicon\.ico$
  static_files: frontend/static/favicon.ico
  upload: frontend/static/favicon\.ico$
  expiration: "2d"

- url: /robots\.txt$
  static_files: frontend/static/robots.txt
  upload: frontend/static/robots\.txt$
  expiration: "2d"

- url: /3d
  static_dir: frontend/static/3d
  expiration: "2d"

- url: /img
  static_dir: frontend/static/img
  expiration: "2d"  

- url: /js
  static_dir: frontend/static/js

- url: /ui5
  static_dir: frontend/static/ui5
  expiration: "2d"
    
- url: /.*
  secure: always
  redirect_http_response_code: 301
  script: auto
