name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - uses: bahmutov/npm-install@v1
    - uses: bahmutov/npm-install@v1
      with:
        working-directory: frontend
    - uses: bahmutov/npm-install@v1
      with:
        working-directory: run
    - run: cp frontend/src/keys.ts.dist frontend/src/keys.ts
    - run: cp common/src/keys.ts.dist common/src/keys.ts
    - run: npm test    
